class BookVo {
  String title;
  String author;
  String publisher;
  String coverImage;
  String description;

  BookVo({
    required this.title,
    required this.author,
    required this.publisher,
    required this.coverImage,
    required this.description,
  });
}

List<BookVo> myBooks = [
  BookVo(
    title: '데미안',
    author: '헤르만 헤세',
    publisher: '민음사',
    coverImage: 'https://minumsa.minumsa.com/wp-content/uploads/bookcover/044_%EB%8D%B0%EB%AF%B8%EC%95%88-300x504.jpg',
    description: '',
  ),
  BookVo(
    title: '여기는 커스터드, 특별한 도시락을 팝니다',
    author: '가토 겐',
    publisher: '필름',
    coverImage: 'https://image.yes24.com/goods/110643268/XL',
    description: '',
  ),
  BookVo(
    title: '하쿠다 사진관',
    author: '허태연',
    publisher: '놀',
    coverImage: 'https://image.yes24.com/goods/110733803/XL',
    description: '',
  ),
  BookVo(
    title: '리더의 말그릇',
    author: '김윤나',
    publisher: '카시오페아',
    coverImage: 'https://image.yes24.com/goods/98897587/XL',
    description: '',
  ),
  BookVo(
    title: '리더의 질문법',
    author: '에드거 샤인, 피터 샤인',
    publisher: '심심',
    coverImage: 'https://image.yes24.com/goods/107997384/XL',
    description: '',
  ),
  BookVo(
    title: '메리골드 마음 세탁소',
    author: '윤정은',
    publisher: '북로망스',
    coverImage: 'https://image.yes24.com/goods/124339743/XL',
    description: '',
  ),
  BookVo(
    title: '메리골드 마음 사진관',
    author: '윤정은',
    publisher: '북로망스',
    coverImage: 'https://image.yes24.com/goods/117716170/XL',
    description: '',
  ),
  BookVo(
    title: '두려움 없는 조직',
    author: '에이미 에드먼드슨',
    publisher: '다산북스',
    coverImage: 'https://image.yes24.com/goods/79633189/XL',
    description: '',
  ),
  BookVo(
    title: '구의 증명',
    author: '최진영',
    publisher: '은행나무',
    coverImage: 'https://image.yes24.com/goods/118578901/XL',
    description: '',
  ),
  BookVo(
    title: '어서오세요, 휴남동 서점입니다',
    author: '황보름',
    publisher: '클레이하우스',
    coverImage: 'https://image.yes24.com/goods/106211628/XL',
    description: '',
  ),
  BookVo(
    title: '밝은 밤',
    author: '최은영',
    publisher: '문학동네',
    coverImage: 'https://image.yes24.com/goods/102687133/XL',
    description: '',
  ),
  BookVo(
    title: '유연한의 힘',
    author: '수잔 애쉬포드',
    publisher: '상상스퀘어',
    coverImage: 'https://image.yes24.com/goods/118755548/XL',
    description: '',
  ),
  BookVo(
    title: '유연함의 힘',
    author: '수잔 애쉬포드',
    publisher: '상상스퀘어',
    coverImage: 'https://image.yes24.com/goods/118755548/XL',
    description: '',
  ),
  BookVo(
    title: '프레임',
    author: '최인철',
    publisher: '21세기북스',
    coverImage: 'https://image.yes24.com/goods/99640630/XL',
    description: '',
  ),
  BookVo(
    title: '사실은 이것도 디자인입니다',
    author: '김성연',
    publisher: '한빛미디어',
    coverImage: 'https://image.yes24.com/goods/120235845/XL',
    description: '',
  ),
  BookVo(
    title: '혼돈의 시대 리더의 탄생',
    author: '도리스 건스 굿윈',
    publisher: '커넥팅',
    coverImage: 'https://image.yes24.com/goods/89400268/XL',
    description: '',
  ),
  BookVo(
    title: '있는 공간, 없는 공간',
    author: '유정수',
    publisher: '쌤앤파커스',
    coverImage: 'https://image.yes24.com/goods/119420884/XL',
    description: '',
  ),
  BookVo(
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'https://image.yes24.com/goods/99308021/XL',
    description: '',
  ),
  BookVo(
    title: '불편한 편의점2',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'https://image.yes24.com/goods/111088149/XL',
    description: '',
  ),
  BookVo(
    title: '불편한 편의점2',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'https://image.yes24.com/goods/111088149/XL',
    description: '',
  ),
  BookVo(
    title: '세상의 마지막 기차역',
    author: '무라세 다케시',
    publisher: '모모',
    coverImage: 'https://image.yes24.com/goods/109308932/XL',
    description: '',
  ),
  BookVo(
    title: '용의자 X의 헌신',
    author: '히가시노 게이고',
    publisher: '재인',
    coverImage: 'https://image.yes24.com/goods/45353675/XL',
    description: '',
  ),
  BookVo(
    title: '타이탄의 도구들',
    author: '팀 페리스',
    publisher: '토네이도',
    coverImage: 'https://image.yes24.com/goods/59262656/XL',
    description: '',
  ),
  BookVo(
    title: '상상하지 말라',
    author: '송길영',
    publisher: '북스톤',
    coverImage: 'https://image.yes24.com/goods/73363770/XL',
    description: '',
  ),
  BookVo(
    title: '인간 실격',
    author: '다자이 오사무',
    publisher: '민음사',
    coverImage: 'https://image.yes24.com/goods/1387488/XL',
    description: '',
  ),
  BookVo(
    title: '부자 아빠 가난한 아빠',
    author: '로버트 기요사키',
    publisher: '황금가지',
    coverImage: 'https://image.yes24.com/momo/TopCate54/MidCate09/5389958.jpg',
    description: '',
  ),
  BookVo(
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    coverImage: 'https://image.yes24.com/goods/102789938/XL',
    description: '',
  ),
  BookVo(
    title: '오직 두 사람',
    author: '김영하',
    publisher: '복복서가',
    coverImage: 'https://image.yes24.com/goods/110508159/XL',
    description: '',
  ),
  BookVo(
    title: '오늘도 개발자가 안 된다고 말했다',
    author: '김중철, 김수지',
    publisher: '디지털북스',
    coverImage: 'https://image.yes24.com/goods/97919905/XL',
    description: '',
  ),
  BookVo(
    title: '갈등을 잘 다루니 인간관계가 쉬워졌습니다',
    author: '이민식',
    publisher: '메이트북스',
    coverImage: 'https://image.yes24.com/goods/70776660/XL',
    description: '',
  ),
  BookVo(
    title: '나미야 잡화점의 기적',
    author: '히가시노 게이고',
    publisher: '현대문학',
    coverImage: 'https://image.yes24.com/goods/116586056/XL',
    description: '',
  ),
  BookVo(
    title: '피프티 피플',
    author: '정세랑',
    publisher: '창비',
    coverImage: 'https://image.yes24.com/momo/TopCate984/MidCate002/98313676.jpg',
    description: '',
  ),
  BookVo(
    title: '보건교사 안은영',
    author: '정세랑',
    publisher: '믿음사',
    coverImage: 'https://image.yes24.com/momo/TopCate0001/kepub/L_482552.jpg',
    description: '',
  ),
  BookVo(
    title: '최고의 팀은 무엇이 다른가',
    author: '대니얼 코일',
    publisher: '웅진지식하우스',
    coverImage: 'https://image.yes24.com/goods/59316692/XL',
    description: '',
  ),
  BookVo(
    title: '쿠팡, 우리가 혁신하는 이유',
    author: '문석현',
    publisher: '갈매나무',
    coverImage: 'https://image.yes24.com/momo/TopCate1053/MidCate003/105222207.jpg',
    description: '',
  ),
  BookVo(
    title: '나는 아마존에서 미래를 다녔다',
    author: '박정준',
    publisher: '한빛비즈',
    coverImage: 'https://image.yes24.com/goods/69770721/XLg',
    description: '',
  ),
  BookVo(
    title: '영어일기 표현사전',
    author: '하명옥',
    publisher: '넥서스',
    coverImage: 'https://image.yes24.com/goods/71954641/XL',
    description: '',
  ),
  BookVo(
    title: '13 Reasons Why',
    author: 'Asher, Jay',
    publisher: 'Razorbil',
    coverImage: 'https://image.yes24.com/goods/35898297/XL',
    description: '',
  ),
  BookVo(
    title: '번역의 탄생',
    author: '이희재',
    publisher: '교양인',
    coverImage: 'https://image.yes24.com/goods/3282824/XL',
    description: '',
  ),
  BookVo(
    title: '살인자의 기억법',
    author: '김영하',
    publisher: '문학동네',
    coverImage: 'https://image.yes24.com/goods/9196011/XL',
    description: '',
  ),
  BookVo(
    title: '그런 사람 또 없습니다',
    author: '원태연',
    publisher: '북로그컴퍼니',
    coverImage: 'https://image.yes24.com/goods/95275828/XL',
    description: '',
  ),
  BookVo(
    title: '사피엔스',
    author: '유발 하라리',
    publisher: '김영사',
    coverImage: 'https://image.yes24.com/goods/23030284/XL',
    description: '',
  ),
  BookVo(
    title: 'English for Developers',
    author: '박재호',
    publisher: '한빛미디어',
    coverImage: 'https://image.yes24.com/Goods/19992192/XL',
    description: '',
  ),
  BookVo(
    title: '트랜드 코리아 2021',
    author: '김난도',
    publisher: '한빛미디어',
    coverImage: 'https://image.yes24.com/Goods/93068681/XL',
    description: '',
  ),
  BookVo(
    title: '언어의 온도',
    author: '이기주',
    publisher: '말글터',
    coverImage: 'https://image.yes24.com/goods/30387696/XL',
    description: '',
  ),
  BookVo(
    title: '1cm 다이빙',
    author: '태수, 문정',
    publisher: '피카',
    coverImage: 'https://image.yes24.com/goods/86543588/XL',
    description: '',
  ),
  BookVo(
    title: 'IT 개발자의 영어 필살기',
    author: '나시노 류타로',
    publisher: '책만',
    coverImage: 'https://image.yes24.com/goods/85385648/XL',
    description: '',
  ),
  BookVo(
    title: '인생의 마지막 순간에서',
    author: '샐리 티스데일',
    publisher: '비잉',
    coverImage: 'https://image.yes24.com/goods/74644329/XL',
    description: '',
  ),
  BookVo(
    title: '지구 끝의 온실',
    author: '김초엽',
    publisher: '자이언트북스',
    coverImage: 'https://image.yes24.com/goods/103026125/XL',
    description: '',
  ),
  BookVo(
    title: 'About Face 4 인터랙션 디자인의 본질',
    author: '엘런 쿠퍼',
    publisher: '에이콘출판사',
    coverImage: 'https://image.yes24.com/momo/TopCate527/MidCate006/51918467.jpg',
    description: '',
  ),
  BookVo(
    title: '우리가 빛의 속도로 갈 수 없다면',
    author: '김초엽',
    publisher: '허블',
    coverImage: 'https://image.yes24.com/goods/74261416/XL',
    description: '',
  ),
  BookVo(
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    coverImage: 'https://image.yes24.com/goods/91065309/XL',
    description: '',
  ),
BookVo(
    title: '꽃을 보듯 너를 본다',
    author: '나태주',
    publisher: '지혜',
    coverImage: 'https://image.yes24.com/goods/24259730/XL',
    description: '',
  ),
  BookVo(
    title: 'UX 원칙',
    author: '윌 그랜트',
    publisher: '에이콘출판사',
    coverImage: 'https://image.yes24.com/goods/80391112/XL',
    description: '',
  ),
  BookVo(
    title: '젊은 베르테르의 슬픔',
    author: '요한 볼프강 폰 괴테',
    publisher: '믿음사',
    coverImage: 'https://image.yes24.com/goods/17386/XL',
    description: '',
  ),
  BookVo(
    title: '이것이 UX/UI 디자인이다',
    author: '조성봉',
    publisher: '위키북스',
    coverImage: 'https://image.yes24.com/goods/90865667/XL',
    description: '',
  ),
  BookVo(
    title: 'UX 디자인 7가지 비밀',
    author: '박지수, 김헌',
    publisher: '안그라픽스',
    coverImage: 'https://image.yes24.com/momo/TopCate243/MidCate009/24281500.jpg',
    description: '',
  ),
  BookVo(
    title: '함께 자라기',
    author: '김창준',
    publisher: '인사이트',
    coverImage: 'https://image.yes24.com/goods/67350256/XL',
    description: '',
  ),
];
