class BookVo {
  String title;
  String author;
  String publisher;
  String coverImage;
  String description;

  BookVo({
    required this.title,
    required this.author,
    required this.publisher,
    required this.coverImage,
    required this.description,
  });
}

List<BookVo> myBooks = [
  BookVo(
    title: '데미안',
    author: '헤르만 헤세',
    publisher: '민음사',
    coverImage: 'https://minumsa.minumsa.com/wp-content/uploads/bookcover/044_%EB%8D%B0%EB%AF%B8%EC%95%88-300x504.jpg',
    description: '',
  ),
  BookVo(
    title: '여기는 커스터드, 특별한 도시락을 팝니다',
    author: '가토 겐',
    publisher: '필름',
    coverImage: 'https://image.yes24.com/goods/110643268/XL',
    description: '',
  ),
  BookVo(
    title: '하쿠다 사진관',
    author: '허태연',
    publisher: '놀',
    coverImage: 'https://image.yes24.com/goods/110733803/XL',
    description: '',
  ),
  BookVo(
    title: '리더의 말그릇',
    author: '김윤나',
    publisher: '카시오페아',
    coverImage: 'https://image.yes24.com/goods/98897587/XL',
    description: '',
  ),
  BookVo(
    title: '리더의 질문법',
    author: '에드거 샤인, 피터 샤인',
    publisher: '심심',
    coverImage: 'https://image.yes24.com/goods/107997384/XL',
    description: '',
  ),
  BookVo(
    title: '메리골드 마음 세탁소',
    author: '윤정은',
    publisher: '북로망스',
    coverImage: 'https://image.yes24.com/goods/124339743/XL',
    description: '',
  ),
  BookVo(
    title: '메리골드 마음 사진관',
    author: '윤정은',
    publisher: '북로망스',
    coverImage: 'https://image.yes24.com/goods/117716170/XL',
    description: '',
  ),
  BookVo(
    title: '두려움 없는 조직',
    author: '에이미 에드먼드슨',
    publisher: '다산북스',
    coverImage: 'https://image.yes24.com/goods/79633189/XL',
    description: '',
  ),
  BookVo(
    title: '구의 증명',
    author: '최진영',
    publisher: '은행나무',
    coverImage: 'https://image.yes24.com/goods/118578901/XL',
    description: '',
  ),
  BookVo(
    title: '어서오세요, 휴남동 서점입니다',
    author: '황보름',
    publisher: '클레이하우스',
    coverImage: 'https://image.yes24.com/goods/106211628/XL',
    description: '',
  ),
  BookVo(
    title: '밝은 밤',
    author: '최은영',
    publisher: '문학동네',
    coverImage: 'https://image.yes24.com/goods/102687133/XL',
    description: '',
  ),
  BookVo(
    title: '유연한의 힘',
    author: '수잔 애쉬포드',
    publisher: '상상스퀘어',
    coverImage: 'https://image.yes24.com/goods/118755548/XL',
    description: '',
  ),
  BookVo(
    title: '유연함의 힘',
    author: '수잔 애쉬포드',
    publisher: '상상스퀘어',
    coverImage: 'https://image.yes24.com/goods/118755548/XL',
    description: '',
  ),
  BookVo(
    title: '프레임',
    author: '최인철',
    publisher: '21세기북스',
    coverImage: 'https://image.yes24.com/goods/99640630/XL',
    description: '',
  ),
  BookVo(
    title: '사실은 이것도 디자인입니다',
    author: '김성연',
    publisher: '한빛미디어',
    coverImage: 'https://image.yes24.com/goods/120235845/XL',
    description: '',
  ),
  BookVo(
    title: '혼돈의 시대 리더의 탄생',
    author: '도리스 건스 굿윈',
    publisher: '커넥팅',
    coverImage: 'https://image.yes24.com/goods/89400268/XL',
    description: '',
  ),
  BookVo(
    title: '있는 공간, 없는 공간',
    author: '유정수',
    publisher: '쌤앤파커스',
    coverImage: 'https://image.yes24.com/goods/119420884/XL',
    description: '',
  ),
  BookVo(
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'https://image.yes24.com/goods/99308021/XL',
    description: '',
  ),
  BookVo(
    title: '불편한 편의점2',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'https://image.yes24.com/goods/111088149/XL',
    description: '',
  ),
  BookVo(
    title: '불편한 편의점2',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'https://image.yes24.com/goods/111088149/XL',
    description: '',
  ),
  BookVo(
    title: '세상의 마지막 기차역',
    author: '무라세 다케시',
    publisher: '모모',
    coverImage: 'https://image.yes24.com/goods/109308932/XL',
    description: '',
  ),
  BookVo(
    title: '용의자 X의 헌신',
    author: '히가시노 게이고',
    publisher: '재인',
    coverImage: 'https://image.yes24.com/goods/45353675/XL',
    description: '',
  ),
  BookVo(
    title: '타이탄의 도구들',
    author: '팀 페리스',
    publisher: '토네이도',
    coverImage: 'https://image.yes24.com/goods/59262656/XL',
    description: '',
  ),
  BookVo(
    title: '상상하지 말라',
    author: '송길영',
    publisher: '북스톤',
    coverImage: 'https://image.yes24.com/goods/73363770/XL',
    description: '',
  ),
  BookVo(
    title: '인간 실격',
    author: '다자이 오사무',
    publisher: '민음사',
    coverImage: 'https://image.yes24.com/goods/1387488/XL',
    description: '',
  ),
  BookVo(
    title: '부자 아빠 가난한 아빠',
    author: '로버트 기요사키',
    publisher: '황금가지',
    coverImage: 'https://image.yes24.com/momo/TopCate54/MidCate09/5389958.jpg',
    description: '',
  ),
  BookVo(
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    coverImage: 'https://image.yes24.com/goods/102789938/XL',
    description: '',
  ),
  BookVo(
    title: '오직 두 사람',
    author: '김영하',
    publisher: '복복서가',
    coverImage: 'https://image.yes24.com/goods/110508159/XL',
    description: '',
  ),
  BookVo(
    title: '오늘도 개발자가 안 된다고 말했다',
    author: '김중철, 김수지',
    publisher: '디지털북스',
    coverImage: 'https://image.yes24.com/goods/97919905/XL',
    description: '',
  ),
  BookVo(
    title: '갈등을 잘 다루니 인간관계가 쉬워졌습니다',
    author: '이민식',
    publisher: '메이트북스',
    coverImage: 'https://image.yes24.com/goods/70776660/XL',
    description: '',
  ),
  BookVo(
    title: '나미야 잡화점의 기적',
    author: '히가시노 게이고',
    publisher: '현대문학',
    coverImage: 'https://image.yes24.com/goods/116586056/XL',
    description: '',
  ),
  BookVo(
    title: '피프티 피플',
    author: '정세랑',
    publisher: '창비',
    coverImage: 'https://image.yes24.com/momo/TopCate984/MidCate002/98313676.jpg',
    description: '',
  ),
  BookVo(
    title: '보건교사 안은영',
    author: '정세랑',
    publisher: '믿음사',
    coverImage: 'https://image.yes24.com/momo/TopCate0001/kepub/L_482552.jpg',
    description: '',
  ),
];
