class BookVo {
  final String title;
  final String author;
  final String publisher;
  final String coverImage;
  final String description;
  final DateTime date;

  BookVo({
    required this.title,
    required this.author,
    required this.publisher,
    required this.coverImage,
    required this.description,
    required this.date,
  });
}

final List<BookVo> myBooks = [
  BookVo(
    title: '황금종이 2',
    author: '조정래',
    publisher: '해냄',
    coverImage: 'assets/images/book/golden2.webp',
    description: '',
    date: DateTime(2025, 3, 25),
  ),
  BookVo(
    title: '황금종이 1',
    author: '조정래',
    publisher: '해냄',
    coverImage: 'assets/images/book/golden1.webp',
    description: '',
    date: DateTime(2025, 3, 2),
  ),
  BookVo(
    title: '데미안',
    author: '헤르만 헤세',
    publisher: '민음사',
    coverImage: 'assets/images/book/demian.webp',
    description: '',
    date: DateTime(2025, 1, 5),
  ),
  BookVo(
    title: '여기는 커스터드, 특별한 도시락을 팝니다',
    author: '가토 겐',
    publisher: '필름',
    coverImage: 'assets/images/book/custud.webp',
    description: '',
    date: DateTime(2024, 12, 5),
  ),
  BookVo(
    title: '하쿠다 사진관',
    author: '허태연',
    publisher: '놀',
    coverImage: 'assets/images/book/hacuta.webp',
    description: '',
    date: DateTime(2020, 12, 5),
  ),
  BookVo(
    title: '리더의 말그릇',
    author: '김윤나',
    publisher: '카시오페아',
    coverImage: 'assets/images/book/leader_dowl.webp',
    description: '',
    date: DateTime(2024, 10, 27),
  ),
  BookVo(
    title: '리더의 질문법',
    author: '에드거 샤인, 피터 샤인',
    publisher: '심심',
    coverImage: 'assets/images/book/leader_inquiry.webp',
    description: '',
    date: DateTime(2024, 10, 5),
  ),
  BookVo(
    title: '메리골드 마음 세탁소',
    author: '윤정은',
    publisher: '북로망스',
    coverImage: 'assets/images/book/marry_gold_laundry.webp',
    description: '',
    date: DateTime(2024, 6, 22),
  ),
  BookVo(
    title: '메리골드 마음 사진관',
    author: '윤정은',
    publisher: '북로망스',
    coverImage: 'assets/images/book/marry_gold_photo.webp',
    description: '',
    date: DateTime(2024, 6, 2),
  ),
  BookVo(
    title: '두려움 없는 조직',
    author: '에이미 에드먼드슨',
    publisher: '다산북스',
    coverImage: 'assets/images/book/fearless_organization.webp',
    description: '',
    date: DateTime(2024, 5, 21),
  ),
  BookVo(
    title: '구의 증명',
    author: '최진영',
    publisher: '은행나무',
    coverImage: 'assets/images/book/gu_proof.webp',
    description: '',
    date: DateTime(2024, 5, 21),
  ),
  BookVo(
    title: '어서오세요, 휴남동 서점입니다',
    author: '황보름',
    publisher: '클레이하우스',
    coverImage: 'assets/images/book/hunamdong.webp',
    description: '',
    date: DateTime(2024, 5, 16),
  ),
  BookVo(
    title: '밝은 밤',
    author: '최은영',
    publisher: '문학동네',
    coverImage: 'assets/images/book/light_night.webp',
    description: '',
    date: DateTime(2024, 5, 7),
  ),
  BookVo(
    title: '유연한의 힘',
    author: '수잔 애쉬포드',
    publisher: '상상스퀘어',
    coverImage: 'assets/images/book/power_flexing.webp',
    description: '',
    date: DateTime(2023, 12, 31),
  ),
  BookVo(
    title: '프레임',
    author: '최인철',
    publisher: '21세기북스',
    coverImage: 'assets/images/book/flame.jpeg',
    description: '',
    date: DateTime(2023, 10, 31),
  ),
  BookVo(
    title: '사실은 이것도 디자인입니다',
    author: '김성연',
    publisher: '한빛미디어',
    coverImage: 'assets/images/book/this_design.webp',
    description: '',
    date: DateTime(2023, 10, 15),
  ),
  BookVo(
    title: '혼돈의 시대 리더의 탄생',
    author: '도리스 건스 굿윈',
    publisher: '커넥팅',
    coverImage: 'assets/images/book/leader_tuarbulent.webp',
    description: '',
    date: DateTime(2023, 9, 2),
  ),
  BookVo(
    title: '있는 공간, 없는 공간',
    author: '유정수',
    publisher: '쌤앤파커스',
    coverImage: 'assets/images/book/place.webp',
    description: '',
    date: DateTime(2023, 7, 30),
  ),
  BookVo(
    title: '불편한 편의점',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'assets/images/book/store_1.webp',
    description: '',
    date: DateTime(2023, 6, 16),
  ),
  BookVo(
    title: '불편한 편의점2',
    author: '김호연',
    publisher: '나무옆의자',
    coverImage: 'assets/images/book/store_2.webp',
    description: '',
    date: DateTime(2023, 7, 1),
  ),
  BookVo(
    title: '세상의 마지막 기차역',
    author: '무라세 다케시',
    publisher: '모모',
    coverImage: 'assets/images/book/last_station.webp',
    description: '',
    date: DateTime(2023, 5, 27),
  ),
  BookVo(
    title: '용의자 X의 헌신',
    author: '히가시노 게이고',
    publisher: '재인',
    coverImage: 'assets/images/book/dedication.webp',
    description: '',
    date: DateTime(2023, 5, 7),
  ),
  BookVo(
    title: '타이탄의 도구들',
    author: '팀 페리스',
    publisher: '토네이도',
    coverImage: 'assets/images/book/titan.webp',
    description: '',
    date: DateTime(2023, 4, 16),
  ),
  BookVo(
    title: '상상하지 말라',
    author: '송길영',
    publisher: '북스톤',
    coverImage: 'assets/images/book/no_imagine.webp',
    description: '',
    date: DateTime(2023, 4, 16),
  ),
  BookVo(
    title: '인간 실격',
    author: '다자이 오사무',
    publisher: '민음사',
    coverImage: 'assets/images/book/disqualification.webp',
    description: '',
    date: DateTime(2022, 11, 4),
  ),
  BookVo(
    title: '부자 아빠 가난한 아빠',
    author: '로버트 기요사키',
    publisher: '황금가지',
    coverImage: 'assets/images/book/dad.webp',
    description: '',
    date: DateTime(2022, 8, 6),
  ),
  BookVo(
    title: '달러구트 꿈 백화점2',
    author: '이미예',
    publisher: '팩토리나인',
    coverImage: 'assets/images/book/dallergut_2.webp',
    description: '',
    date: DateTime(2022, 8, 6),
  ),
  BookVo(
    title: '오직 두 사람',
    author: '김영하',
    publisher: '복복서가',
    coverImage: 'assets/images/book/two_person.webp',
    description: '',
    date: DateTime(2022, 7, 16),
  ),
  BookVo(
    title: '오늘도 개발자가 안 된다고 말했다',
    author: '김중철, 김수지',
    publisher: '디지털북스',
    coverImage: 'assets/images/book/no_developer.webp',
    description: '',
    date: DateTime(2022, 1, 29),
  ),
  BookVo(
    title: '갈등을 잘 다루니 인간관계가 쉬워졌습니다',
    author: '이민식',
    publisher: '메이트북스',
    coverImage: 'assets/images/book/conflict.webp',
    description: '',
    date: DateTime(2021, 12, 30),
  ),
  BookVo(
    title: '나미야 잡화점의 기적',
    author: '히가시노 게이고',
    publisher: '현대문학',
    coverImage: 'assets/images/book/namiya.webp',
    description: '',
    date: DateTime(2021, 10, 24),
  ),
  BookVo(
    title: '피프티 피플',
    author: '정세랑',
    publisher: '창비',
    coverImage: 'assets/images/book/fifty_people.webp',
    description: '',
    date: DateTime(2021, 9, 29),
  ),
  BookVo(
    title: '보건교사 안은영',
    author: '정세랑',
    publisher: '믿음사',
    coverImage: 'assets/images/book/health_teacher.webp',
    description: '',
    date: DateTime(2021, 9, 24),
  ),
  BookVo(
    title: '최고의 팀은 무엇이 다른가',
    author: '대니얼 코일',
    publisher: '웅진지식하우스',
    coverImage: 'assets/images/book/best_group.webp',
    description: '',
    date: DateTime(2021, 8, 22),
  ),
  BookVo(
    title: '쿠팡, 우리가 혁신하는 이유',
    author: '문석현',
    publisher: '갈매나무',
    coverImage: 'assets/images/book/coupang.webp',
    description: '',
    date: DateTime(2021, 8, 14),
  ),
  BookVo(
    title: '나는 아마존에서 미래를 다녔다',
    author: '박정준',
    publisher: '한빛비즈',
    coverImage: 'assets/images/book/amazon.webp',
    description: '',
    date: DateTime(2021, 8, 10),
  ),
  BookVo(
    title: '영어일기 표현사전',
    author: '하명옥',
    publisher: '넥서스',
    coverImage: 'assets/images/book/diary.webp',
    description: '',
    date: DateTime(2021, 3, 30),
  ),
  BookVo(
    title: '13 Reasons Why',
    author: 'Asher, Jay',
    publisher: 'Razorbil',
    coverImage: 'assets/images/book/13reasons.webp',
    description: '',
    date: DateTime(2021, 3, 26),
  ),
  BookVo(
    title: '번역의 탄생',
    author: '이희재',
    publisher: '교양인',
    coverImage: 'assets/images/book/translation.webp',
    description: '',
    date: DateTime(2021, 3, 26),
  ),
  BookVo(
    title: '살인자의 기억법',
    author: '김영하',
    publisher: '문학동네',
    coverImage: 'assets/images/book/murder.webp',
    description: '',
    date: DateTime(2021, 2, 11),
  ),
  BookVo(
    title: '그런 사람 또 없습니다',
    author: '원태연',
    publisher: '북로그컴퍼니',
    coverImage: 'assets/images/book/no_person.webp',
    description: '',
    date: DateTime(2021, 2, 10),
  ),
  BookVo(
    title: '사피엔스',
    author: '유발 하라리',
    publisher: '김영사',
    coverImage: 'assets/images/book/safiance.webp',
    description: '',
    date: DateTime(2021, 2, 4),
  ),
  BookVo(
    title: 'English for Developers',
    author: '박재호',
    publisher: '한빛미디어',
    coverImage: 'assets/images/book/developer_english.webp',
    description: '',
    date: DateTime(2020, 12, 30),
  ),
  BookVo(
    title: '트랜드 코리아 2021',
    author: '김난도',
    publisher: '한빛미디어',
    coverImage: 'assets/images/book/trand_korea.webp',
    description: '',
    date: DateTime(2020, 12, 28),
  ),
  BookVo(
    title: '언어의 온도',
    author: '이기주',
    publisher: '말글터',
    coverImage: 'assets/images/book/language_ondo.webp',
    description: '',
    date: DateTime(2020, 12, 21),
  ),
  BookVo(
    title: '1cm 다이빙',
    author: '태수, 문정',
    publisher: '피카',
    coverImage: 'assets/images/book/1cm.webp',
    description: '',
    date: DateTime(2020, 12, 16),
  ),
  BookVo(
    title: 'IT 개발자의 영어 필살기',
    author: '나시노 류타로',
    publisher: '책만',
    coverImage: 'assets/images/book/IT_developer.webp',
    description: '',
    date: DateTime(2020, 12, 17),
  ),
  BookVo(
    title: '인생의 마지막 순간에서',
    author: '샐리 티스데일',
    publisher: '비잉',
    coverImage: 'assets/images/book/last_moment.webp',
    description: '',
    date: DateTime(2020, 12, 12),
  ),
  BookVo(
    title: '지구 끝의 온실',
    author: '김초엽',
    publisher: '자이언트북스',
    coverImage: 'assets/images/book/green_house.webp',
    description: '',
    date: DateTime(2020, 12, 4),
  ),
  BookVo(
    title: 'About Face 4 인터랙션 디자인의 본질',
    author: '엘런 쿠퍼',
    publisher: '에이콘출판사',
    coverImage: 'assets/images/book/face4.webp',
    description: '',
    date: DateTime(2020, 12, 13),
  ),
  BookVo(
    title: '우리가 빛의 속도로 갈 수 없다면',
    author: '김초엽',
    publisher: '허블',
    coverImage: 'assets/images/book/light_speed.webp',
    description: '',
    date: DateTime(2020, 11, 28),
  ),
  BookVo(
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    coverImage: 'assets/images/book/dallergut_1.webp',
    description: '',
    date: DateTime(2020, 11, 22),
  ),
  BookVo(
    title: '꽃을 보듯 너를 본다',
    author: '나태주',
    publisher: '지혜',
    coverImage: 'assets/images/book/flower.webp',
    description: '',
    date: DateTime(2020, 11, 20),
  ),
  BookVo(
    title: 'UX 원칙',
    author: '윌 그랜트',
    publisher: '에이콘출판사',
    coverImage: 'assets/images/book/ux_principle.webp',
    description: '',
    date: DateTime(2020, 11, 21),
  ),
  BookVo(
    title: '젊은 베르테르의 슬픔',
    author: '요한 볼프강 폰 괴테',
    publisher: '믿음사',
    coverImage: 'assets/images/book/sorrow.webp',
    description: '',
    date: DateTime(2020, 11, 16),
  ),
  BookVo(
    title: '이것이 UX/UI 디자인이다',
    author: '조성봉',
    publisher: '위키북스',
    coverImage: 'assets/images/book/ux_ui_design.webp',
    description: '',
    date: DateTime(2020, 11, 13),
  ),
  BookVo(
    title: 'UX 디자인 7가지 비밀',
    author: '박지수, 김헌',
    publisher: '안그라픽스',
    coverImage: 'assets/images/book/ux_secret.webp',
    description: '',
    date: DateTime(2020, 11, 8),
  ),
  BookVo(
    title: '함께 자라기',
    author: '김창준',
    publisher: '인사이트',
    coverImage: 'assets/images/book/together.webp',
    description: '',
    date: DateTime(2020, 9, 1),
  ),
];
